export const STORY_PENDING = 'STORY_PENDING';
export const STORY_ERROR = 'STORY_ERROR';
export const STORY_SUCCESS = 'STORY_SUCCESS';
export const STORY_SUCCESS_NEXT = 'STORY_SUCCESS_NEXT';
export const STORY_SUCCESS_SCROLL = 'STORY_SUCCESS_SCROLL';
